### PR TITLE
flexible webapp init

### PR DESCRIPTION
**Pull request by fredrikt**
Make the shared webapp init code flexible enough to be used by eduid-api.

I'm not entirely sure I think it was worth it, hence the request for review by all three of you.

/Fredrik

### CODE REVIEW

**Comment by enriquepablo** [comment]
It doesn't look bad to me... But I  agree that eduid-api gets little benefit. I guess the deciding factor should be whether you want / need [the dependencies of eduid-common[webapp]](https://github.com/SUNET/eduid-common/blob/master/setup.py#L12) in every deployment of eduid-api.

**Comment by enriquepablo** [comment]
> ProxyFix
> init_logging
> init_sentry

At the most basic level I would probably also try to add a common way of accesing configuration, and a common way of being testable. (And statsd?)

> What do you say about moving those parts to a common init_app and the rest in the current init_app to a shared webapp_init_app in the eduid_webapp repo?

eduid-webapp has no common code so far, just specific apps. I'd leave it that way, and keep on putting common code in eduid-common. 
Instead, I think we would need  a different "dependency profile" more or less for each different `(xxx_)init_app` primitive function in eduid-common, ("dependency profile" in the sense of a setuptools.setup() extras_require entry).

If we limit eduid-common by the dependencies of eduid-api or  other uncommon packages, nothing will fit in it and everything will end up in eduid-webapp... and the idea (or at least one idea I clung to ;-) was that any of the apps in eduid-webapp could live in it own package, only depending on eduid-common.

**Comment by johanlundberg** [comment]
Yeah, I take the suggestion of creating a webapp_init_app back after reading your post Enrique. I agree with you that the best way is by starting to fix the dependencies and keep shared code in eduid-common. As you said, the point of eduid-webapp is just to collect standalone apps in one place not to tangle them in each other :)

**Comment by enriquepablo** [comment]
I think that the question then is to decide whether it is worth having this PR and a new "dependency profile" in terms of the benefit that eduid-api will get (mainly benefit on maintainability and readability within the context of eduID, since I think it clearly will be more code).
My  opinion is that yes it is worth, but just barely;  I wouldn't put any effort into defending this view.

**Pull request closed without merging**
